version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/code
    depends_on:
      - frontend

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/app

  docs:
    build: ./docs
    ports:
      - "4000:3000"
    volumes:
      - ./docs:/docs
