/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as SobreImport } from "./routes/sobre";
import { Route as NormasImport } from "./routes/normas";
import { Route as IndexImport } from "./routes/index";
import { Route as HomeIndexImport } from "./routes/home/index";
import { Route as AuthIndexImport } from "./routes/auth/index";
import { Route as HomePeriodicTableImport } from "./routes/home/periodicTable";
import { Route as HomeChatImport } from "./routes/home/chat";
import { Route as AuthRegistroImport } from "./routes/auth/registro";
import { Route as AuthRecuperarsenhaImport } from "./routes/auth/recuperarsenha";
import { Route as AuthLoginImport } from "./routes/auth/login";
import { Route as HomeExperimentosIndexImport } from "./routes/home/experimentos/index";
import { Route as HomeExperimentosVulcaobicarbonatoImport } from "./routes/home/experimentos/vulcaobicarbonato";
import { Route as HomeExperimentosNovoExperimentoImport } from "./routes/home/experimentos/novo-experimento";
import { Route as HomeExperimentosDensidadeLiquidosImport } from "./routes/home/experimentos/densidadeLiquidos";
import { Route as HomeExperimentosCromatografiaImport } from "./routes/home/experimentos/cromatografia";

// Create/Update Routes

const SobreRoute = SobreImport.update({
  id: "/sobre",
  path: "/sobre",
  getParentRoute: () => rootRoute,
} as any);

const NormasRoute = NormasImport.update({
  id: "/normas",
  path: "/normas",
  getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as any);

const HomeIndexRoute = HomeIndexImport.update({
  id: "/home/",
  path: "/home/",
  getParentRoute: () => rootRoute,
} as any);

const AuthIndexRoute = AuthIndexImport.update({
  id: "/auth/",
  path: "/auth/",
  getParentRoute: () => rootRoute,
} as any);

const HomePeriodicTableRoute = HomePeriodicTableImport.update({
  id: "/home/periodicTable",
  path: "/home/periodicTable",
  getParentRoute: () => rootRoute,
} as any);

const HomeChatRoute = HomeChatImport.update({
  id: "/home/chat",
  path: "/home/chat",
  getParentRoute: () => rootRoute,
} as any);

const AuthRegistroRoute = AuthRegistroImport.update({
  id: "/auth/registro",
  path: "/auth/registro",
  getParentRoute: () => rootRoute,
} as any);

const AuthRecuperarsenhaRoute = AuthRecuperarsenhaImport.update({
  id: "/auth/recuperarsenha",
  path: "/auth/recuperarsenha",
  getParentRoute: () => rootRoute,
} as any);

const AuthLoginRoute = AuthLoginImport.update({
  id: "/auth/login",
  path: "/auth/login",
  getParentRoute: () => rootRoute,
} as any);

const HomeExperimentosIndexRoute = HomeExperimentosIndexImport.update({
  id: "/home/experimentos/",
  path: "/home/experimentos/",
  getParentRoute: () => rootRoute,
} as any);

const HomeExperimentosVulcaobicarbonatoRoute =
  HomeExperimentosVulcaobicarbonatoImport.update({
    id: "/home/experimentos/vulcaobicarbonato",
    path: "/home/experimentos/vulcaobicarbonato",
    getParentRoute: () => rootRoute,
  } as any);

const HomeExperimentosNovoExperimentoRoute =
  HomeExperimentosNovoExperimentoImport.update({
    id: "/home/experimentos/novo-experimento",
    path: "/home/experimentos/novo-experimento",
    getParentRoute: () => rootRoute,
  } as any);

const HomeExperimentosDensidadeLiquidosRoute =
  HomeExperimentosDensidadeLiquidosImport.update({
    id: "/home/experimentos/densidadeLiquidos",
    path: "/home/experimentos/densidadeLiquidos",
    getParentRoute: () => rootRoute,
  } as any);

const HomeExperimentosCromatografiaRoute =
  HomeExperimentosCromatografiaImport.update({
    id: "/home/experimentos/cromatografia",
    path: "/home/experimentos/cromatografia",
    getParentRoute: () => rootRoute,
  } as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    "/normas": {
      id: "/normas";
      path: "/normas";
      fullPath: "/normas";
      preLoaderRoute: typeof NormasImport;
      parentRoute: typeof rootRoute;
    };
    "/sobre": {
      id: "/sobre";
      path: "/sobre";
      fullPath: "/sobre";
      preLoaderRoute: typeof SobreImport;
      parentRoute: typeof rootRoute;
    };
    "/auth/login": {
      id: "/auth/login";
      path: "/auth/login";
      fullPath: "/auth/login";
      preLoaderRoute: typeof AuthLoginImport;
      parentRoute: typeof rootRoute;
    };
    "/auth/recuperarsenha": {
      id: "/auth/recuperarsenha";
      path: "/auth/recuperarsenha";
      fullPath: "/auth/recuperarsenha";
      preLoaderRoute: typeof AuthRecuperarsenhaImport;
      parentRoute: typeof rootRoute;
    };
    "/auth/registro": {
      id: "/auth/registro";
      path: "/auth/registro";
      fullPath: "/auth/registro";
      preLoaderRoute: typeof AuthRegistroImport;
      parentRoute: typeof rootRoute;
    };
    "/home/chat": {
      id: "/home/chat";
      path: "/home/chat";
      fullPath: "/home/chat";
      preLoaderRoute: typeof HomeChatImport;
      parentRoute: typeof rootRoute;
    };
    "/home/periodicTable": {
      id: "/home/periodicTable";
      path: "/home/periodicTable";
      fullPath: "/home/periodicTable";
      preLoaderRoute: typeof HomePeriodicTableImport;
      parentRoute: typeof rootRoute;
    };
    "/auth/": {
      id: "/auth/";
      path: "/auth";
      fullPath: "/auth";
      preLoaderRoute: typeof AuthIndexImport;
      parentRoute: typeof rootRoute;
    };
    "/home/": {
      id: "/home/";
      path: "/home";
      fullPath: "/home";
      preLoaderRoute: typeof HomeIndexImport;
      parentRoute: typeof rootRoute;
    };
    "/home/experimentos/cromatografia": {
      id: "/home/experimentos/cromatografia";
      path: "/home/experimentos/cromatografia";
      fullPath: "/home/experimentos/cromatografia";
      preLoaderRoute: typeof HomeExperimentosCromatografiaImport;
      parentRoute: typeof rootRoute;
    };
    "/home/experimentos/densidadeLiquidos": {
      id: "/home/experimentos/densidadeLiquidos";
      path: "/home/experimentos/densidadeLiquidos";
      fullPath: "/home/experimentos/densidadeLiquidos";
      preLoaderRoute: typeof HomeExperimentosDensidadeLiquidosImport;
      parentRoute: typeof rootRoute;
    };
    "/home/experimentos/novo-experimento": {
      id: "/home/experimentos/novo-experimento";
      path: "/home/experimentos/novo-experimento";
      fullPath: "/home/experimentos/novo-experimento";
      preLoaderRoute: typeof HomeExperimentosNovoExperimentoImport;
      parentRoute: typeof rootRoute;
    };
    "/home/experimentos/vulcaobicarbonato": {
      id: "/home/experimentos/vulcaobicarbonato";
      path: "/home/experimentos/vulcaobicarbonato";
      fullPath: "/home/experimentos/vulcaobicarbonato";
      preLoaderRoute: typeof HomeExperimentosVulcaobicarbonatoImport;
      parentRoute: typeof rootRoute;
    };
    "/home/experimentos/": {
      id: "/home/experimentos/";
      path: "/home/experimentos";
      fullPath: "/home/experimentos";
      preLoaderRoute: typeof HomeExperimentosIndexImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/normas": typeof NormasRoute;
  "/sobre": typeof SobreRoute;
  "/auth/login": typeof AuthLoginRoute;
  "/auth/recuperarsenha": typeof AuthRecuperarsenhaRoute;
  "/auth/registro": typeof AuthRegistroRoute;
  "/home/chat": typeof HomeChatRoute;
  "/home/periodicTable": typeof HomePeriodicTableRoute;
  "/auth": typeof AuthIndexRoute;
  "/home": typeof HomeIndexRoute;
  "/home/experimentos/cromatografia": typeof HomeExperimentosCromatografiaRoute;
  "/home/experimentos/densidadeLiquidos": typeof HomeExperimentosDensidadeLiquidosRoute;
  "/home/experimentos/novo-experimento": typeof HomeExperimentosNovoExperimentoRoute;
  "/home/experimentos/vulcaobicarbonato": typeof HomeExperimentosVulcaobicarbonatoRoute;
  "/home/experimentos": typeof HomeExperimentosIndexRoute;
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/normas": typeof NormasRoute;
  "/sobre": typeof SobreRoute;
  "/auth/login": typeof AuthLoginRoute;
  "/auth/recuperarsenha": typeof AuthRecuperarsenhaRoute;
  "/auth/registro": typeof AuthRegistroRoute;
  "/home/chat": typeof HomeChatRoute;
  "/home/periodicTable": typeof HomePeriodicTableRoute;
  "/auth": typeof AuthIndexRoute;
  "/home": typeof HomeIndexRoute;
  "/home/experimentos/cromatografia": typeof HomeExperimentosCromatografiaRoute;
  "/home/experimentos/densidadeLiquidos": typeof HomeExperimentosDensidadeLiquidosRoute;
  "/home/experimentos/novo-experimento": typeof HomeExperimentosNovoExperimentoRoute;
  "/home/experimentos/vulcaobicarbonato": typeof HomeExperimentosVulcaobicarbonatoRoute;
  "/home/experimentos": typeof HomeExperimentosIndexRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/": typeof IndexRoute;
  "/normas": typeof NormasRoute;
  "/sobre": typeof SobreRoute;
  "/auth/login": typeof AuthLoginRoute;
  "/auth/recuperarsenha": typeof AuthRecuperarsenhaRoute;
  "/auth/registro": typeof AuthRegistroRoute;
  "/home/chat": typeof HomeChatRoute;
  "/home/periodicTable": typeof HomePeriodicTableRoute;
  "/auth/": typeof AuthIndexRoute;
  "/home/": typeof HomeIndexRoute;
  "/home/experimentos/cromatografia": typeof HomeExperimentosCromatografiaRoute;
  "/home/experimentos/densidadeLiquidos": typeof HomeExperimentosDensidadeLiquidosRoute;
  "/home/experimentos/novo-experimento": typeof HomeExperimentosNovoExperimentoRoute;
  "/home/experimentos/vulcaobicarbonato": typeof HomeExperimentosVulcaobicarbonatoRoute;
  "/home/experimentos/": typeof HomeExperimentosIndexRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/normas"
    | "/sobre"
    | "/auth/login"
    | "/auth/recuperarsenha"
    | "/auth/registro"
    | "/home/chat"
    | "/home/periodicTable"
    | "/auth"
    | "/home"
    | "/home/experimentos/cromatografia"
    | "/home/experimentos/densidadeLiquidos"
    | "/home/experimentos/novo-experimento"
    | "/home/experimentos/vulcaobicarbonato"
    | "/home/experimentos";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/normas"
    | "/sobre"
    | "/auth/login"
    | "/auth/recuperarsenha"
    | "/auth/registro"
    | "/home/chat"
    | "/home/periodicTable"
    | "/auth"
    | "/home"
    | "/home/experimentos/cromatografia"
    | "/home/experimentos/densidadeLiquidos"
    | "/home/experimentos/novo-experimento"
    | "/home/experimentos/vulcaobicarbonato"
    | "/home/experimentos";
  id:
    | "__root__"
    | "/"
    | "/normas"
    | "/sobre"
    | "/auth/login"
    | "/auth/recuperarsenha"
    | "/auth/registro"
    | "/home/chat"
    | "/home/periodicTable"
    | "/auth/"
    | "/home/"
    | "/home/experimentos/cromatografia"
    | "/home/experimentos/densidadeLiquidos"
    | "/home/experimentos/novo-experimento"
    | "/home/experimentos/vulcaobicarbonato"
    | "/home/experimentos/";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  NormasRoute: typeof NormasRoute;
  SobreRoute: typeof SobreRoute;
  AuthLoginRoute: typeof AuthLoginRoute;
  AuthRecuperarsenhaRoute: typeof AuthRecuperarsenhaRoute;
  AuthRegistroRoute: typeof AuthRegistroRoute;
  HomeChatRoute: typeof HomeChatRoute;
  HomePeriodicTableRoute: typeof HomePeriodicTableRoute;
  AuthIndexRoute: typeof AuthIndexRoute;
  HomeIndexRoute: typeof HomeIndexRoute;
  HomeExperimentosCromatografiaRoute: typeof HomeExperimentosCromatografiaRoute;
  HomeExperimentosDensidadeLiquidosRoute: typeof HomeExperimentosDensidadeLiquidosRoute;
  HomeExperimentosNovoExperimentoRoute: typeof HomeExperimentosNovoExperimentoRoute;
  HomeExperimentosVulcaobicarbonatoRoute: typeof HomeExperimentosVulcaobicarbonatoRoute;
  HomeExperimentosIndexRoute: typeof HomeExperimentosIndexRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NormasRoute: NormasRoute,
  SobreRoute: SobreRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRecuperarsenhaRoute: AuthRecuperarsenhaRoute,
  AuthRegistroRoute: AuthRegistroRoute,
  HomeChatRoute: HomeChatRoute,
  HomePeriodicTableRoute: HomePeriodicTableRoute,
  AuthIndexRoute: AuthIndexRoute,
  HomeIndexRoute: HomeIndexRoute,
  HomeExperimentosCromatografiaRoute: HomeExperimentosCromatografiaRoute,
  HomeExperimentosDensidadeLiquidosRoute:
    HomeExperimentosDensidadeLiquidosRoute,
  HomeExperimentosNovoExperimentoRoute: HomeExperimentosNovoExperimentoRoute,
  HomeExperimentosVulcaobicarbonatoRoute:
    HomeExperimentosVulcaobicarbonatoRoute,
  HomeExperimentosIndexRoute: HomeExperimentosIndexRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/normas",
        "/sobre",
        "/auth/login",
        "/auth/recuperarsenha",
        "/auth/registro",
        "/home/chat",
        "/home/periodicTable",
        "/auth/",
        "/home/",
        "/home/experimentos/cromatografia",
        "/home/experimentos/densidadeLiquidos",
        "/home/experimentos/novo-experimento",
        "/home/experimentos/vulcaobicarbonato",
        "/home/experimentos/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/normas": {
      "filePath": "normas.tsx"
    },
    "/sobre": {
      "filePath": "sobre.tsx"
    },
    "/auth/login": {
      "filePath": "auth/login.tsx"
    },
    "/auth/recuperarsenha": {
      "filePath": "auth/recuperarsenha.tsx"
    },
    "/auth/registro": {
      "filePath": "auth/registro.tsx"
    },
    "/home/chat": {
      "filePath": "home/chat.tsx"
    },
    "/home/periodicTable": {
      "filePath": "home/periodicTable.tsx"
    },
    "/auth/": {
      "filePath": "auth/index.tsx"
    },
    "/home/": {
      "filePath": "home/index.tsx"
    },
    "/home/experimentos/cromatografia": {
      "filePath": "home/experimentos/cromatografia.tsx"
    },
    "/home/experimentos/densidadeLiquidos": {
      "filePath": "home/experimentos/densidadeLiquidos.tsx"
    },
    "/home/experimentos/novo-experimento": {
      "filePath": "home/experimentos/novo-experimento.tsx"
    },
    "/home/experimentos/vulcaobicarbonato": {
      "filePath": "home/experimentos/vulcaobicarbonato.tsx"
    },
    "/home/experimentos/": {
      "filePath": "home/experimentos/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
