[book]
authors = ["Arthur Rocha"]
language = "en"
multilingual = false
src = "src"
title = "Documentãção IA no Lab"

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output]

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
