[book]
authors = ["arthurdev06"]
language = "en"
multilingual = false
src = "src"
title = "IA no Lab Documentation"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]